[package]
name = "elrond-mint-contract-abi"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.elrond-mint-contract]
path = ".."

[dependencies.elrond-wasm]
version = "0.17.4"

[dependencies.elrond-wasm-debug]
version = "0.17.4"
